# Triggered via
# curl -X POST https://api.github.com/repos/onxpnet/exercise-app/dispatches \
# -H 'Accept: application/vnd.github.everest-preview+json' \
# -H "Authorization: token $GITHUB_TOKEN" \
# --data '{"event_type": "build", "client_payload": {"tag": "v1.0.1"}}'

# access data from: ${{ github.event.client_payload.tag }}

name: Build Docker Image

on:
  repository_dispatch:
    types: [build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.tag }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install jest
        run: npm ci

      - name: Run test
        run: npx jest

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: glendmaatita/exercise-app:${{ github.event.client_payload.tag }}

  notify:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        run: |
          curl -v -X POST "${{secrets.DISCORD_WEBHOOKS_URL}}" -H "Content-Type: application/json" -d "{\"content\": \"Build Exercise App on tag ${{ github.event.client_payload.tag }} has been finished. Check this on https://github.com/onxpnet/exercise-app/actions/runs/${{ github.run_id }}\", \"username\": \"github-bot\", \"avatar_url\": \"https://cdn.discordapp.com/attachments/892612412014997557/1226787592725463040/gitlab-logo-600.png?ex=662609fa&is=661394fa&hm=ab695f97e42f571d6d98dd5a9f9fa8db1c295fdf16290489b21430069443ce8b&\"}"